repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
#    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

- repo: local

  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=120, --target-version=py37]
      exclude: ^venv/

    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      language: system
      types: [python]
      args: [--py37-plus]

    - id: flake8
      name: Flake8
      entry: flake8
      language: system
      types: [python]
      args: []

#    - id: reorder-python-imports
#      name: reorder-python-imports
#      entry: reorder-python-imports
#      language: system
#      types: [python]
#      args: [--py37-plus]
#
#    - id: yesqa
#      name: yesqa
#      entry: yesqa
#      language: system
#      types: [python]

#    - id: autoflake
#      name: autoflake
#      entry: autoflake
#      language: system
#      types: [python]
#      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
#